- name: verify homebrew presence
  command: which brew
  register: brew_present
  changed_when: false
  ignore_errors: true

- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_present|failed

- name: update homebrew and its packages
  homebrew: update_homebrew=yes upgrade_all=yes
  when: brew_present
  ignore_errors: true
