- name: be sure homebrew packages of tools are installed
  homebrew: name={{ item }} state=latest
  with_items: '{{ brew_packages }}'

- name: be sure homebrew cask packages of all tools are installed
  homebrew_cask: name={{ item }} state=present
  with_items: '{{ brew_cask_packages }}'

- name: be sure all browsers are installed
  homebrew_cask: name={{ item }} state=present
  with_items: '{{ browsers }}'